# Generated by Django 3.1.7 on 2021-04-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='members',
        ),
    ]
