# Generated by Django 3.1.7 on 2021-04-03 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(verbose_name='block number')),
            ],
            options={
                'verbose_name': 'block',
                'verbose_name_plural': 'blocks',
            },
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='complex name')),
                ('address', models.CharField(max_length=50, verbose_name='complex address')),
            ],
            options={
                'verbose_name': 'complex',
                'verbose_name_plural': 'complexs',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='unit phone number')),
                ('no', models.IntegerField(verbose_name='unit number')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.block', verbose_name='block')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('owner_family', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='family.family', verbose_name='familly')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.complex', verbose_name='complex'),
        ),
    ]
